executables:
  moscoviumorange-p:
    ghc-options: -main-is Main -prof -fprof-auto
    source-dirs: src
    main: Main.hs
  moscoviumorange:
    source-dirs: src
    main: Main.hs
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
  - base
  - optparse-applicative
  - optparse-text
  # common
  - aeson
  - aeson-pretty
  - bytestring
  - stm
  - split
  - text
  - time
  - thyme
  - binary
  - lens
  - binary-orphans
  - mtl
  - old-locale
  - directory
  - pretty-simple
  - string-conversions
  - network
  - unordered-containers
  - containers
  - rainbox
  - rainbow
  - unix
  - mtl
name: MoscoviumOrange
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
default-extensions: 
  - LambdaCase
